### ISSUE TITLE
The "0" Displacement Dilemma

### ISSUE THREAD

**Issue by steve3743** [rr-/CRC-manipulator#11]
Okay, there's this problem:

![number_dont_match_up](https://cloud.githubusercontent.com/assets/20365207/16705745/5ad6acfc-4561-11e6-8e1d-00c0cd576fe8.png)

It works fine when you're putting in letters; it also works with numbers that are none zeroes; but if you slide in two or more zeroes their placed in the front instead of the chosen positions. Please fix this. Thank You.

Keep up the awesome work, I love that there's a gui. :D

**Comment by rr-** [comment]
Good catch. The culprit is `QLineEdit`'s [`inputMask` behavior](http://doc.qt.io/qt-4.8/qlineedit.html#inputMask-prop) that strips "blank characters", e.g. the characters that the input is filled with by default. In this case those were zeroes. I've replaced them with hashes, which makes the input slightly less intuitive, but fixes this bug.

**Comment by steve3743** [comment]
Thanks for the quick fix; I'll test it straight away.

**Comment by steve3743** [comment]
It works. :D
